//! `crdts` is a library of thoroughly-tested, serializable CRDT's
//! ported from the riak_dt library to rust.
#![crate_type = "lib"]
#![deny(missing_docs)]

pub use error::{Result, Error};
pub use gcounter::GCounter;
pub use lwwreg::LWWReg;
pub use mvreg::MVReg;
pub use orswot::Orswot;
pub use pncounter::PNCounter;
pub use map::Map;
pub use ctx::{ReadCtx, AddCtx, RmCtx};
pub use vclock::{VClock, Dot, Actor};
pub use traits::{CvRDT, CmRDT, Causal, FunkyCvRDT, FunkyCmRDT};


/// `traits` contains Trait commonly used when working with CRDT's
pub mod traits;
/// `lwwreg` contains the last-write-wins register.
pub mod lwwreg;
/// `mvreg` contains the multi-value register.
pub mod mvreg;
/// `vclock` contains the vector clock.
pub mod vclock;
/// `orswot` contains the addition-biased or-set without tombstone.
pub mod orswot;
/// `gcounter` contains the grow-only counter
pub mod gcounter;
/// `pncounter` contains the positive-negative counter
pub mod pncounter;
/// `map` contains a map CRDT which allows nesting of CRDT's
pub mod map;
/// `ctx` contains the read and write contexts
pub mod ctx;

/// `error` contains possible Error codes generated by CRDT operations
pub mod error;

#[macro_use]
extern crate serde_derive;
extern crate serde;
