use std::fmt::Debug;

use serde::Serialize;
use serde::de::DeserializeOwned;

use vclock::{VClock, Actor};

/// State based CRDT's replicate by transmitting the entire CRDT state
pub trait CvRDT {
    /// User chosen error type
    type Error: Debug;

    /// Merge the given CRDT into the current CRDT.
    fn merge(&mut self, other: &Self) -> Result<(), Self::Error>;
}

/// Operation based CRDT's replicate with ops
pub trait CmRDT {
    /// User chosen error type
    type Error: Debug;

    /// Op defines a mutation to the CRDT.
    /// As long as Op's from one actor are replayed in exactly the same order they
    /// were generated by that actor, the CRDT will converge. In other words, we must
    /// have a total ordering on each actors operations, while requiring only a partial
    /// order over all ops.
    /// E.g.
    ///
    /// Actor A produces ops A1, A2
    /// Actor B produces ops B1, B2
    ///
    /// the only valid orderings are:
    /// A1 < A2 < B1 < B2
    /// A1 < B1 < A2 < B2
    /// B1 < A1 < A2 < B2
    /// A1 < B1 < B2 < A2
    /// B1 < A1 < B2 < A2
    /// B1 < B2 < A1 < A2
    ///
    /// Applying ops in any of the valid orders will converge to the same CRDT state
    ///
    /// Op's must be idempotent, meaning any Op may be applied more than once.
    type Op: Debug + Clone + Send + Serialize + DeserializeOwned;

    /// Apply an Op to the CRDT
    fn apply(&mut self, op: Self::Op) -> Result<(), Self::Error>;
}

/// Crdt's are causal if they are built on top of vector clocks
pub trait Causal<A: Actor> {
    /// Truncate the CRDT to remove anything before the clock
    fn truncate(&mut self, clock: &VClock<A>);
}
